const status_validation = {
    "1. En recherche": 1,
    "2. En relance recherche": 2,
    "2.1 Bilan de zone": 3,
    "3. Validation en cours": 4,
    "4.1 En attente CRVT/Visée/Pano": 5,
    "4.2 En attente CRVT": 6,
    "4.3 CRVT à valider (MOE SFR)": 7,
    "4.4 En attente reprise CRVT": 8,
    "5. En attente validation des visées FH": 9,
    "6. En attente MAJ coordonnées RSU": 10,
    "7. Prospect validé" : 11,
    "8. Abandonné": 12,
    "à valider": 13,
    "Prospect KO": 14,
    "MAV à déposer": 15,
    "Abandonné": 16,
    "En Recherche": 17,
    "En Relance Recherche": 18,
    "Validation En Cours": 19,
    "En attente PANO": 20,
    "En attente visées FH": 21,
    "En attente validation des visées FH": 22,
    "En attente MAJ coordonnées RSU / CRVT": 23,
    "En attente DC": 24,
    "Prospect Validé": 25,
   "GO CONSTR SFR": 26,
}
export {status_validation}